*** Settings ***
Documentation       Test generated by Teasy Generator
...
...                 Executable tests presents in this file.

Resource            ../pages/commons/hooks.pages.commons.robot
Resource            ../config/page_register.config.robot

Test Setup          Start Test
Test Teardown       Finish Test

*** Test Cases ***
TEASY: Generated Test 0
     Example Keyword
     Example Keyword 3
     Example Keyword 5

TEASY: Generated Test 1
     Example Keyword
     Example Keyword 4

TEASY: Generated Test 2
     Example Keyword 2
     Example Keyword

TEASY: Generated Test 3
     Example Keyword 2
     Example Keyword 2

