import fileDownload from 'js-file-download'

let amountTestsGenerated = 0

const testName = "TEASY: Generated Test "
const testFile = {
    settings_section: "*** Settings ***\n",
    documentation: "Documentation       Test generated by Teasy Generator\n",
    documentation_white_line: "...\n",
    documentation_description: "...                 Executable tests presents in this file.\n\n",
    import_hooks: "Resource            ../pages/commons/hooks.pages.commons.robot\n",
    import_pages: "Resource            ../config/page_register.config.robot\n\n",
    test_setup: "Test Setup          Start Test\n",
    test_teardown: "Test Teardown       Finish Test\n\n",
    test_cases_section: "*** Test Cases ***\n",
    test_cases: ""
}

const mountRobotFile = ({ testSequences, filename }) => {
    testSequences.forEach(sequence => {
        testFile.test_cases += createTestCase(sequence) + "\n"
    });
    fileDownload( mountTestFile(), filename)
}

const createTestCase = sequence => {
    let testCaseName = testName + amountTestsGenerated
    let keywords = ""
    sequence.forEach(keyword => {
       keywords += "     " + keyword + "\n" 
    });
    amountTestsGenerated++
    return testCaseName + "\n" + keywords
}

const mountTestFile = () => (
    testFile.settings_section +
    testFile.documentation +
    testFile.documentation_white_line +
    testFile.documentation_description +
    testFile.import_hooks +
    testFile.import_pages +
    testFile.test_setup +
    testFile.test_teardown +
    testFile.test_cases_section +
    testFile.test_cases
)

export { mountRobotFile }